on:
  pull_request:
    branches: -master
  push:
    branches:
      - master
      - main
      - ci-cd-workflows

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
        # This command builds an APK for Android
      - name: Save APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
        # This step saves the APK as an artifact, which you can download later
      - run: flutter build ios --no-codesign
        # This command builds an IPA for iOS
      - name: Save IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-Release-IPA
          path: build/ios/archive/Runner.ipa
        # This step saves the IPA as an artifact, which you can download later
